### ISSUE TITLE
company/about

### ISSUE THREAD

**Issue by paul-armstrong** [mayank30/arm-solution#1]
We are a creative website,software and app  design company in Liverpool, Merseyside, working for clients throughout the United Kingdom. We build responsive websites software solutions and apps for desktop, laptop, tablet and smartphone. We work with companies to create beautiful, effective and user-friendly solutions that are designed and built to provide a return on investment and generate new leads, conversions and revenue.

All our clients are different, but they all share the need to have a solution built to generate revenue streams, establish communication channels or streamline business operations.

We leverage our large knowledge base to deliver solutions that meet customers' needs, business and budget expectations.

KEEP the OUR BUSINESS PHILOSOPHY part

KEEP OUR STRENGTHS part

and were the logos are change them for xpress logo turnthemusicup.co.uk logo arm solutions beauty hut

on the main picture change to since 2017

thant should be it for the about us page

also change the pictures so its not obviously copied

**Comment by mayank30** [comment]
Best ...

**Comment by mayank30** [comment]
Done Changes Code Deployed.. Closing ticket
