### ISSUE TITLE
company/quality managment 

### ISSUE THREAD

**Issue by paul-armstrong** [mayank30/arm-solution#2]
change this "Arm Solutions performs quality assurance throughout the entire software development lifecycle with QA team members being involved at all stages. A Lead QA specialist is assigned at the commencement of each project and is involved into initial business analysis and requirements specification. Such a simultaneous interaction of our development and QA teams provides for a better understanding of the project scope and the client’s business objectives. A typical QA lifecycle at Arm Solutions includes the following phases:

to this"
Arm Solutions performs quality assurance throughout the entire website and web app development lifecycle with QA team members being involved at all stages. A Lead QA specialist is assigned at the commencement of each project and is involved into initial business analysis and requirements specification. Such a simultaneous interaction of our development and QA teams provides for a better understanding of the project scope and the client’s business objectives. A typical QA lifecycle at Arm Solutions includes the following phases:

were it says independent QA department change iflixion to Arm Solutions 

change the pictures

**Comment by mayank30** [comment]
Done Changes Code Deployed.. Closing ticket
